### ISSUE TITLE
Trabajo suma, resta, multiplicación  binarios, hexadecimal, octal

### ISSUE THREAD

**Issue by irwingsael** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-irwingsael#1]
[TECNOLOGICO NACIONAL DE MÉXICO_Irwing.pdf](https://github.com/user-attachments/files/16841442/TECNOLOGICO.NACIONAL.DE.MEXICO_Irwing.pdf)

**Comment by kevinMazarelloJOSE** [comment]
portada: 25
Procedimiento:25
Figuras, ilustraciones, fotografías: 25
Resultados y conclusiones: 25
Calificación de la práctica: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
